import type { BrowseFilter, Creator, Sector, Strategy } from "../types/strategyTypes";

export type {
  BrowseFilter,
  Creator,
  GraphEdge,
  GraphNode,
  Sector,
  Strategy,
} from "../types/strategyTypes";

export const sectors: Array<"All" | Sector> = [
  "All",
  "CEX",
  "DeFi",
  "Mixed",
  "Funding",
  "Basis",
  "LP/Hedge",
];

export const browseFilters: BrowseFilter[] = [
  "Daily Hot",
  "New",
  "Top Gainer",
  "Top Volume",
];

export const connectedExchanges = [
  "Aave",
  "Binance",
  "Bybit",
  "Curve",
  "GMX",
  "Hyperliquid",
  "Lido",
  "Morpho",
  "OKX",
  "Uniswap V3",
  "Upbit",
];

export const creators: Record<string, Creator> = {
  "quant.kim": {
    id: "quant.kim",
    name: "Kim Quant",
    handle: "@quant.kim",
    bio: "Funding-rate and perp-basis strategies with strict hedge caps.",
    exchanges: ["Binance", "Bybit"],
    chains: ["Ethereum", "BNB Chain"],
    walletAddress: "0x7C2F...A19F",
    tradedCapital: 214000,
    tradingProfit: 18400,
  },
  "nari.trade": {
    id: "nari.trade",
    name: "Nari Trade",
    handle: "@nari.trade",
    bio: "Stablecoin route builder across CEX liquidity and DeFi pools.",
    exchanges: ["Coinbase", "Curve", "Uniswap V3"],
    chains: ["Ethereum", "Base"],
    walletAddress: "0x42B8...2E1C",
    tradedCapital: 318000,
    tradingProfit: 24320,
  },
  slotmaker: {
    id: "slotmaker",
    name: "Slotmaker",
    handle: "@slotmaker",
    bio: "LST, lending, and basis rotations for low drawdown portfolios.",
    exchanges: ["Lido", "Aave", "Uniswap V3"],
    chains: ["Ethereum"],
    walletAddress: "0x9Da3...7710",
    tradedCapital: 166000,
    tradingProfit: 10220,
  },
  "mira.exec": {
    id: "mira.exec",
    name: "Mira Exec",
    handle: "@mira.exec",
    bio: "Momentum execution ladders for liquid CEX markets.",
    exchanges: ["OKX", "Binance"],
    chains: ["Solana", "Ethereum"],
    tradedCapital: 96000,
    tradingProfit: 8900,
  },
  "yuna.delta": {
    id: "yuna.delta",
    name: "Yuna Delta",
    handle: "@yuna.delta",
    bio: "Delta-neutral hedges across perp venues and DeFi vaults.",
    exchanges: ["GMX", "Hyperliquid", "Binance"],
    chains: ["Arbitrum", "Ethereum"],
    walletAddress: "0x1162...E0d9",
    tradedCapital: 188000,
    tradingProfit: 15300,
  },
  "juno.base": {
    id: "juno.base",
    name: "Juno Base",
    handle: "@juno.base",
    bio: "Stablecoin loop yield with conservative utilization bands.",
    exchanges: ["Aave", "Morpho", "Curve"],
    chains: ["Base", "Ethereum"],
    walletAddress: "0x0B17...C3AA",
    tradedCapital: 132000,
    tradingProfit: 7200,
  },
  seoulbot: {
    id: "seoulbot",
    name: "Seoulbot",
    handle: "@seoulbot",
    bio: "KRW premium and CEX spread monitoring for regional flows.",
    exchanges: ["Upbit", "Binance", "Bithumb"],
    chains: ["Bitcoin", "Ethereum"],
    tradedCapital: 146000,
    tradingProfit: 19900,
  },
  dawnlabs: {
    id: "dawnlabs",
    name: "Dawn Labs",
    handle: "@dawnlabs",
    bio: "LP delta hedging with options overlays and range controls.",
    exchanges: ["Uniswap V3", "Deribit", "Aave"],
    chains: ["Ethereum", "Arbitrum"],
    walletAddress: "0x6335...019B",
    tradedCapital: 104000,
    tradingProfit: 6300,
  },
  "alex.macro": {
    id: "alex.macro",
    name: "Alex Macro",
    handle: "@alex.macro",
    bio: "Cross-venue basis sweeps with macro event filters.",
    exchanges: ["dYdX", "Binance", "Aave"],
    chains: ["Ethereum", "Cosmos"],
    tradedCapital: 118000,
    tradingProfit: 9400,
  },
  chainpilot: {
    id: "chainpilot",
    name: "Chainpilot",
    handle: "@chainpilot",
    bio: "Bridge timing and on-chain liquidity displacement strategies.",
    exchanges: ["Camelot", "Uniswap V3", "Binance"],
    chains: ["Arbitrum", "Ethereum"],
    walletAddress: "0xaF55...8172",
    tradedCapital: 87000,
    tradingProfit: 7800,
  },
};

export const strategies: Strategy[] = [
  {
    id: "btc-funding-carry",
    title: "BTC Perp Funding Carry",
    creatorId: "quant.kim",
    primarySector: "CEX",
    sectors: ["CEX", "Funding"],
    venues: ["Binance", "Bybit"],
    chains: ["Ethereum", "BNB Chain"],
    pnlSeries: [0, 680, 1120, 890, 1740, 2290, 2140, 3180, 3950, 4210, 5020, 5770],
    realizedPnl: 5770,
    pnlPct: 8.9,
    deployedCapital: 65000,
    dailyVolume: 184000,
    winRate: 71,
    maxDrawdown: 3.8,
    traders: 241,
    status: "Live",
    createdAt: "2h",
    nodes: [
      { id: "collateral", label: "USDT", x: 34, y: 78 },
      { id: "binance", label: "Binance", x: 142, y: 42 },
      { id: "bybit", label: "Bybit", x: 142, y: 116 },
      { id: "hedge", label: "Delta Hedge", x: 286, y: 78 },
    ],
    edges: [
      { from: "collateral", to: "binance", label: "long spot" },
      { from: "collateral", to: "bybit", label: "short perp" },
      { from: "binance", to: "hedge", label: "funding" },
      { from: "bybit", to: "hedge", label: "rebalance" },
    ],
  },
  {
    id: "usdc-depeg-router",
    title: "USDC Depeg Arb Router",
    creatorId: "nari.trade",
    primarySector: "Mixed",
    sectors: ["Mixed", "CEX", "DeFi"],
    venues: ["Coinbase", "Curve", "Uniswap V3"],
    chains: ["Ethereum", "Base"],
    pnlSeries: [0, -210, 640, 1480, 2310, 1980, 4140, 6260, 7140, 6810, 9230, 11040],
    realizedPnl: 11040,
    pnlPct: 14.6,
    deployedCapital: 76000,
    dailyVolume: 492000,
    winRate: 64,
    maxDrawdown: 5.9,
    traders: 384,
    status: "Live",
    createdAt: "5h",
    nodes: [
      { id: "coinbase", label: "Coinbase", x: 38, y: 42 },
      { id: "curve", label: "Curve", x: 150, y: 78 },
      { id: "uniswap", label: "Uniswap", x: 262, y: 42 },
      { id: "treasury", label: "USDC Vault", x: 262, y: 116 },
    ],
    edges: [
      { from: "coinbase", to: "curve", label: "mint" },
      { from: "curve", to: "uniswap", label: "route" },
      { from: "uniswap", to: "treasury", label: "settle" },
      { from: "treasury", to: "coinbase", label: "redeem" },
    ],
  },
  {
    id: "eth-lst-basis",
    title: "ETH LST Basis Rotation",
    creatorId: "slotmaker",
    primarySector: "DeFi",
    sectors: ["DeFi", "Basis"],
    venues: ["Lido", "Aave", "Uniswap V3"],
    chains: ["Ethereum"],
    pnlSeries: [0, 320, 770, 690, 1320, 1810, 2230, 2550, 2940, 3330, 3720, 4010],
    realizedPnl: 4010,
    pnlPct: 6.3,
    deployedCapital: 63500,
    dailyVolume: 97000,
    winRate: 76,
    maxDrawdown: 2.7,
    traders: 137,
    status: "Live",
    createdAt: "1d",
    nodes: [
      { id: "eth", label: "ETH", x: 36, y: 78 },
      { id: "lido", label: "Lido", x: 140, y: 42 },
      { id: "aave", label: "Aave", x: 140, y: 116 },
      { id: "dex", label: "Uniswap", x: 286, y: 78 },
    ],
    edges: [
      { from: "eth", to: "lido", label: "stake" },
      { from: "lido", to: "aave", label: "borrow" },
      { from: "aave", to: "dex", label: "rotate" },
      { from: "dex", to: "eth", label: "close" },
    ],
  },
  {
    id: "sol-momentum-ladder",
    title: "SOL Momentum Ladder",
    creatorId: "mira.exec",
    primarySector: "CEX",
    sectors: ["CEX"],
    venues: ["OKX", "Binance"],
    chains: ["Solana", "Ethereum"],
    pnlSeries: [0, 420, 880, 620, 1510, 2680, 2440, 3170, 3530, 3290, 4880, 4590],
    realizedPnl: 4590,
    pnlPct: 11.1,
    deployedCapital: 41300,
    dailyVolume: 229000,
    winRate: 59,
    maxDrawdown: 6.8,
    traders: 198,
    status: "Cooling",
    createdAt: "3h",
    nodes: [
      { id: "signal", label: "Signal", x: 34, y: 78 },
      { id: "okx", label: "OKX", x: 142, y: 42 },
      { id: "binance", label: "Binance", x: 142, y: 116 },
      { id: "risk", label: "Risk Cap", x: 286, y: 78 },
    ],
    edges: [
      { from: "signal", to: "okx", label: "entry" },
      { from: "signal", to: "binance", label: "entry" },
      { from: "okx", to: "risk", label: "scale" },
      { from: "binance", to: "risk", label: "exit" },
    ],
  },
  {
    id: "gmx-basis-hedge",
    title: "GMX Basis + Hedge",
    creatorId: "yuna.delta",
    primarySector: "Mixed",
    sectors: ["Mixed", "DeFi", "Basis", "LP/Hedge"],
    venues: ["GMX", "Hyperliquid", "Binance"],
    chains: ["Arbitrum", "Ethereum"],
    pnlSeries: [0, 260, 510, 1320, 1180, 2140, 3020, 3670, 4180, 4720, 4390, 5180],
    realizedPnl: 5180,
    pnlPct: 7.4,
    deployedCapital: 70000,
    dailyVolume: 143000,
    winRate: 68,
    maxDrawdown: 4.4,
    traders: 164,
    status: "Live",
    createdAt: "8h",
    nodes: [
      { id: "gmx", label: "GMX", x: 42, y: 78 },
      { id: "vault", label: "Vault", x: 142, y: 42 },
      { id: "hyper", label: "Hyperliquid", x: 142, y: 116 },
      { id: "binance", label: "Binance", x: 286, y: 78 },
    ],
    edges: [
      { from: "gmx", to: "vault", label: "GLP" },
      { from: "vault", to: "hyper", label: "hedge" },
      { from: "hyper", to: "binance", label: "basis" },
      { from: "binance", to: "gmx", label: "rebalance" },
    ],
  },
  {
    id: "stable-loop-yield",
    title: "Stablecoin Loop Yield",
    creatorId: "juno.base",
    primarySector: "DeFi",
    sectors: ["DeFi", "LP/Hedge"],
    venues: ["Aave", "Morpho", "Curve"],
    chains: ["Base", "Ethereum"],
    pnlSeries: [0, 180, 350, 530, 790, 1080, 1360, 1520, 1710, 2050, 2310, 2490],
    realizedPnl: 2490,
    pnlPct: 4.1,
    deployedCapital: 60700,
    dailyVolume: 51000,
    winRate: 83,
    maxDrawdown: 1.6,
    traders: 96,
    status: "Live",
    createdAt: "2d",
    nodes: [
      { id: "vault", label: "Vault", x: 36, y: 78 },
      { id: "aave", label: "Aave", x: 136, y: 42 },
      { id: "morpho", label: "Morpho", x: 136, y: 116 },
      { id: "curve", label: "Curve", x: 286, y: 78 },
    ],
    edges: [
      { from: "vault", to: "aave", label: "supply" },
      { from: "aave", to: "morpho", label: "loop" },
      { from: "morpho", to: "curve", label: "swap" },
      { from: "curve", to: "vault", label: "harvest" },
    ],
  },
  {
    id: "kimchi-spread-watch",
    title: "Kimchi Spread Watch",
    creatorId: "seoulbot",
    primarySector: "CEX",
    sectors: ["CEX", "Basis"],
    venues: ["Upbit", "Binance", "Bithumb"],
    chains: ["Bitcoin", "Ethereum"],
    pnlSeries: [0, 910, 460, 1280, 2010, 1780, 3410, 2960, 4220, 5230, 4880, 6390],
    realizedPnl: 6390,
    pnlPct: 15.8,
    deployedCapital: 40500,
    dailyVolume: 318000,
    winRate: 62,
    maxDrawdown: 7.1,
    traders: 301,
    status: "Live",
    createdAt: "6h",
    nodes: [
      { id: "upbit", label: "Upbit", x: 38, y: 42 },
      { id: "bithumb", label: "Bithumb", x: 38, y: 116 },
      { id: "fx", label: "KRW/USD", x: 166, y: 78 },
      { id: "binance", label: "Binance", x: 286, y: 78 },
    ],
    edges: [
      { from: "upbit", to: "fx", label: "premium" },
      { from: "bithumb", to: "fx", label: "spread" },
      { from: "fx", to: "binance", label: "hedge" },
      { from: "binance", to: "upbit", label: "settle" },
    ],
  },
  {
    id: "lp-delta-neutral",
    title: "LP Delta Neutral Hedge",
    creatorId: "dawnlabs",
    primarySector: "LP/Hedge",
    sectors: ["Mixed", "DeFi", "LP/Hedge"],
    venues: ["Uniswap V3", "Deribit", "Aave"],
    chains: ["Ethereum", "Arbitrum"],
    pnlSeries: [0, -180, 390, 760, 1210, 990, 1560, 2210, 2470, 2680, 3020, 2870],
    realizedPnl: 2870,
    pnlPct: 5.2,
    deployedCapital: 55200,
    dailyVolume: 86000,
    winRate: 70,
    maxDrawdown: 3.3,
    traders: 112,
    status: "Paused",
    createdAt: "4d",
    nodes: [
      { id: "uni", label: "Uniswap", x: 42, y: 78 },
      { id: "aave", label: "Aave", x: 146, y: 42 },
      { id: "deribit", label: "Deribit", x: 146, y: 116 },
      { id: "risk", label: "Gamma Cap", x: 286, y: 78 },
    ],
    edges: [
      { from: "uni", to: "aave", label: "borrow" },
      { from: "aave", to: "deribit", label: "option" },
      { from: "deribit", to: "risk", label: "delta" },
      { from: "risk", to: "uni", label: "range" },
    ],
  },
  {
    id: "eth-perp-basis-sweep",
    title: "ETH Perp Basis Sweep",
    creatorId: "alex.macro",
    primarySector: "Mixed",
    sectors: ["Mixed", "CEX", "Basis"],
    venues: ["dYdX", "Binance", "Aave"],
    chains: ["Ethereum", "Cosmos"],
    pnlSeries: [0, 510, 880, 1420, 1210, 1970, 2650, 3020, 2760, 3380, 3910, 3520],
    realizedPnl: 3520,
    pnlPct: 9.7,
    deployedCapital: 36300,
    dailyVolume: 126000,
    winRate: 66,
    maxDrawdown: 4.9,
    traders: 149,
    status: "Live",
    createdAt: "11h",
    nodes: [
      { id: "signal", label: "Basis", x: 38, y: 78 },
      { id: "dydx", label: "dYdX", x: 142, y: 42 },
      { id: "binance", label: "Binance", x: 142, y: 116 },
      { id: "aave", label: "Aave", x: 286, y: 78 },
    ],
    edges: [
      { from: "signal", to: "dydx", label: "short" },
      { from: "signal", to: "binance", label: "long" },
      { from: "dydx", to: "aave", label: "margin" },
      { from: "binance", to: "aave", label: "settle" },
    ],
  },
  {
    id: "arb-bridge-latency",
    title: "ARB Bridge Latency Arb",
    creatorId: "chainpilot",
    primarySector: "DeFi",
    sectors: ["DeFi", "Mixed"],
    venues: ["Camelot", "Uniswap V3", "Binance"],
    chains: ["Arbitrum", "Ethereum"],
    pnlSeries: [0, 330, 940, 780, 1880, 2210, 2640, 2490, 3560, 4020, 3770, 4460],
    realizedPnl: 4460,
    pnlPct: 12.3,
    deployedCapital: 36200,
    dailyVolume: 117000,
    winRate: 61,
    maxDrawdown: 6.2,
    traders: 173,
    status: "Cooling",
    createdAt: "9h",
    nodes: [
      { id: "arb", label: "Arbitrum", x: 38, y: 78 },
      { id: "camelot", label: "Camelot", x: 142, y: 42 },
      { id: "uniswap", label: "Uniswap", x: 142, y: 116 },
      { id: "binance", label: "Binance", x: 286, y: 78 },
    ],
    edges: [
      { from: "arb", to: "camelot", label: "local" },
      { from: "arb", to: "uniswap", label: "bridge" },
      { from: "camelot", to: "binance", label: "hedge" },
      { from: "uniswap", to: "binance", label: "exit" },
    ],
  },
];
