import type { BrowseFilter, Creator, Sector, Strategy } from "../types/strategyTypes";

export type {
  BrowseFilter,
  Creator,
  DisclosureMode,
  GraphEdge,
  GraphNode,
  ProductType,
  Sector,
  Strategy,
} from "../types/strategyTypes";

export const sectors: Array<"All" | Sector> = [
  "All",
  "Perp Index",
  "Funding",
  "Basis",
  "Market Neutral",
  "Momentum",
  "Liquidity",
  "Volatility",
  "Risk Hedge",
];

export const productTypes: Array<"All" | Strategy["productType"]> = [
  "All",
  "Index",
  "Quant",
];

export const browseFilters: BrowseFilter[] = [
  "Featured",
  "Perp Index",
  "Funding Carry",
  "Market Neutral",
  "Tactical Quant",
];

export const connectedExchanges = ["Hyperliquid"];

export const creators: Record<string, Creator> = {
  "quant.kim": {
    id: "quant.kim",
    name: "Kim Quant",
    handle: "@quant.kim",
    bio: "Hyperliquid funding and basis strategies with strict margin controls.",
    exchanges: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    walletAddress: "0x7C2F...A19F",
    tradedCapital: 284000,
    tradingProfit: 31400,
  },
  "nari.trade": {
    id: "nari.trade",
    name: "Nari Trade",
    handle: "@nari.trade",
    bio: "Public perp index baskets and transparent Hyperliquid rebalance rules.",
    exchanges: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    walletAddress: "0x42B8...2E1C",
    tradedCapital: 338000,
    tradingProfit: 28620,
  },
  slotmaker: {
    id: "slotmaker",
    name: "Slotmaker",
    handle: "@slotmaker",
    bio: "Hyperliquid maker inventory strategies with low turnover and tight drawdown caps.",
    exchanges: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    walletAddress: "0x9Da3...7710",
    tradedCapital: 216000,
    tradingProfit: 16220,
  },
  "mira.exec": {
    id: "mira.exec",
    name: "Mira Exec",
    handle: "@mira.exec",
    bio: "Momentum and volatility execution ladders for liquid Hyperliquid perp markets.",
    exchanges: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    tradedCapital: 196000,
    tradingProfit: 18900,
  },
  "yuna.delta": {
    id: "yuna.delta",
    name: "Yuna Delta",
    handle: "@yuna.delta",
    bio: "Delta-neutral and cross-margin hedging systems on Hyperliquid.",
    exchanges: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    walletAddress: "0x1162...E0d9",
    tradedCapital: 248000,
    tradingProfit: 23300,
  },
  "juno.core": {
    id: "juno.core",
    name: "Juno Core",
    handle: "@juno.core",
    bio: "Collateral-aware defensive baskets for Hyperliquid accounts.",
    exchanges: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    walletAddress: "0x0B17...C3AA",
    tradedCapital: 172000,
    tradingProfit: 11200,
  },
  seoulbot: {
    id: "seoulbot",
    name: "Seoulbot",
    handle: "@seoulbot",
    bio: "Orderflow and liquidation imbalance models for Hyperliquid majors.",
    exchanges: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    tradedCapital: 186000,
    tradingProfit: 21900,
  },
  dawnlabs: {
    id: "dawnlabs",
    name: "Dawn Labs",
    handle: "@dawnlabs",
    bio: "Volatility breakout and range-risk systems on Hyperliquid perps.",
    exchanges: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    walletAddress: "0x6335...019B",
    tradedCapital: 164000,
    tradingProfit: 14300,
  },
  "alex.macro": {
    id: "alex.macro",
    name: "Alex Macro",
    handle: "@alex.macro",
    bio: "Macro-filtered ETH and BTC perp basis sweeps on Hyperliquid.",
    exchanges: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    tradedCapital: 178000,
    tradingProfit: 17400,
  },
  chainpilot: {
    id: "chainpilot",
    name: "Chainpilot",
    handle: "@chainpilot",
    bio: "Hyperliquid liquidity displacement and cross-margin defense strategies.",
    exchanges: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    walletAddress: "0xaF55...8172",
    tradedCapital: 147000,
    tradingProfit: 11800,
  },
};

export const strategies: Strategy[] = [
  {
    id: "hl-majors-index",
    title: "Hyperliquid Majors Index",
    creatorId: "nari.trade",
    primarySector: "Perp Index",
    sectors: ["Perp Index"],
    productType: "Index",
    disclosure: "Full",
    venues: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    markets: ["Hyperliquid Perp DEX"],
    assetClasses: ["BTC", "ETH", "SOL", "HYPE perps"],
    pnlSeries: [0, 420, 760, 610, 1240, 1680, 2090, 2510, 3110, 3860, 4380, 5120],
    realizedPnl: 5120,
    pnlPct: 7.9,
    deployedCapital: 119000,
    dailyVolume: 440000,
    winRate: 72,
    maxDrawdown: 3.4,
    nodes: [
      { id: "weights", label: "Public Weights", x: 34, y: 78 },
      { id: "btc", label: "BTC-PERP", x: 150, y: 34 },
      { id: "eth", label: "ETH-PERP", x: 150, y: 78 },
      { id: "sol", label: "SOL / HYPE", x: 150, y: 122 },
      { id: "rebalance", label: "Rebalance", x: 286, y: 78 },
    ],
    edges: [
      { from: "weights", to: "btc", label: "35%" },
      { from: "weights", to: "eth", label: "30%" },
      { from: "weights", to: "sol", label: "35%" },
      { from: "sol", to: "rebalance", label: "daily" },
    ],
  },
  {
    id: "hl-alt-rotation-index",
    title: "Hyperliquid Alt Rotation Index",
    creatorId: "mira.exec",
    primarySector: "Perp Index",
    sectors: ["Perp Index", "Momentum"],
    productType: "Index",
    disclosure: "Full",
    venues: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    markets: ["Hyperliquid Perp DEX"],
    assetClasses: ["Altcoin perps", "Momentum basket"],
    pnlSeries: [0, 690, 1120, 930, 2110, 2860, 3440, 3920, 4710, 5560, 6710, 7830],
    realizedPnl: 7830,
    pnlPct: 14.9,
    deployedCapital: 75000,
    dailyVolume: 510000,
    winRate: 64,
    maxDrawdown: 6.7,
    nodes: [
      { id: "universe", label: "Alt Universe", x: 34, y: 78 },
      { id: "rank", label: "Momentum Rank", x: 150, y: 78 },
      { id: "hype", label: "HYPE", x: 286, y: 34 },
      { id: "sol", label: "SOL", x: 286, y: 78 },
      { id: "longtail", label: "FET / PURR", x: 286, y: 122 },
    ],
    edges: [
      { from: "universe", to: "rank", label: "7d / 30d" },
      { from: "rank", to: "hype", label: "top" },
      { from: "rank", to: "sol", label: "top" },
      { from: "rank", to: "longtail", label: "rotate" },
    ],
  },
  {
    id: "hl-defensive-collateral-index",
    title: "Hyperliquid Defensive Collateral Index",
    creatorId: "juno.core",
    primarySector: "Perp Index",
    sectors: ["Perp Index", "Risk Hedge"],
    productType: "Index",
    disclosure: "Full",
    venues: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    markets: ["Hyperliquid Perp DEX"],
    assetClasses: ["USDC collateral", "Major perps", "HYPE perp"],
    pnlSeries: [0, 160, 310, 520, 740, 920, 1090, 1280, 1520, 1870, 2160, 2480],
    realizedPnl: 2480,
    pnlPct: 4.3,
    deployedCapital: 69200,
    dailyVolume: 164000,
    winRate: 81,
    maxDrawdown: 1.9,
    nodes: [
      { id: "collateral", label: "USDC Core", x: 34, y: 78 },
      { id: "majors", label: "BTC / ETH", x: 154, y: 46 },
      { id: "hype", label: "HYPE", x: 154, y: 110 },
      { id: "risk", label: "Risk Bands", x: 286, y: 78 },
    ],
    edges: [
      { from: "collateral", to: "majors", label: "low beta" },
      { from: "collateral", to: "hype", label: "small cap" },
      { from: "majors", to: "risk", label: "cap" },
      { from: "hype", to: "risk", label: "cap" },
    ],
  },
  {
    id: "hl-btc-funding-carry",
    title: "Hyperliquid BTC Funding Carry",
    creatorId: "quant.kim",
    primarySector: "Funding",
    sectors: ["Funding", "Market Neutral"],
    productType: "Quant",
    disclosure: "PerformanceOnly",
    venues: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    markets: ["Hyperliquid Perp DEX"],
    assetClasses: ["BTC perp", "USDC collateral"],
    pnlSeries: [0, 520, 980, 1240, 1710, 2290, 2710, 3480, 4290, 5180, 6070, 7240],
    realizedPnl: 7240,
    pnlPct: 11.7,
    deployedCapital: 62000,
    dailyVolume: 390000,
    winRate: 74,
    maxDrawdown: 3.6,
    nodes: [
      { id: "funding", label: "Funding Term", x: 34, y: 78 },
      { id: "btc", label: "BTC-PERP", x: 150, y: 42 },
      { id: "collateral", label: "USDC Margin", x: 150, y: 116 },
      { id: "hedge", label: "Delta Gate", x: 286, y: 78 },
    ],
    edges: [
      { from: "funding", to: "btc", label: "enter" },
      { from: "funding", to: "collateral", label: "size" },
      { from: "btc", to: "hedge", label: "neutralize" },
      { from: "collateral", to: "hedge", label: "margin" },
    ],
  },
  {
    id: "hl-eth-basis-carry",
    title: "Hyperliquid ETH Basis Carry",
    creatorId: "alex.macro",
    primarySector: "Basis",
    sectors: ["Basis", "Funding"],
    productType: "Quant",
    disclosure: "PerformanceOnly",
    venues: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    markets: ["Hyperliquid Perp DEX"],
    assetClasses: ["ETH perp", "USDC collateral"],
    pnlSeries: [0, 340, 710, 650, 1290, 1830, 2240, 2660, 3180, 3710, 4290, 4960],
    realizedPnl: 4960,
    pnlPct: 8.1,
    deployedCapital: 61200,
    dailyVolume: 276000,
    winRate: 69,
    maxDrawdown: 4.1,
    nodes: [
      { id: "basis", label: "ETH Basis", x: 38, y: 78 },
      { id: "eth", label: "ETH-PERP", x: 150, y: 42 },
      { id: "funding", label: "Funding", x: 150, y: 116 },
      { id: "macro", label: "Macro Filter", x: 286, y: 78 },
    ],
    edges: [
      { from: "basis", to: "eth", label: "price" },
      { from: "basis", to: "funding", label: "carry" },
      { from: "funding", to: "macro", label: "gate" },
      { from: "eth", to: "macro", label: "size" },
    ],
  },
  {
    id: "hl-market-neutral-grid",
    title: "Hyperliquid Market Neutral Grid",
    creatorId: "slotmaker",
    primarySector: "Market Neutral",
    sectors: ["Market Neutral", "Liquidity"],
    productType: "Quant",
    disclosure: "PerformanceOnly",
    venues: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    markets: ["Hyperliquid Perp DEX"],
    assetClasses: ["Major perps", "USDC collateral"],
    pnlSeries: [0, 280, 620, 910, 1180, 1530, 1940, 2420, 2980, 3630, 4210, 5130],
    realizedPnl: 5130,
    pnlPct: 6.8,
    deployedCapital: 75400,
    dailyVolume: 338000,
    winRate: 78,
    maxDrawdown: 2.5,
    nodes: [
      { id: "marks", label: "Live Marks", x: 34, y: 78 },
      { id: "bands", label: "Maker Bands", x: 150, y: 42 },
      { id: "inventory", label: "Inventory Cap", x: 150, y: 116 },
      { id: "rebalance", label: "Neutralize", x: 286, y: 78 },
    ],
    edges: [
      { from: "marks", to: "bands", label: "spread" },
      { from: "marks", to: "inventory", label: "skew" },
      { from: "bands", to: "rebalance", label: "fills" },
      { from: "inventory", to: "rebalance", label: "cap" },
    ],
  },
  {
    id: "hl-liquidation-reversal",
    title: "Hyperliquid Liquidation Reversal",
    creatorId: "seoulbot",
    primarySector: "Liquidity",
    sectors: ["Liquidity", "Momentum"],
    productType: "Quant",
    disclosure: "PerformanceOnly",
    venues: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    markets: ["Hyperliquid Perp DEX"],
    assetClasses: ["Liquid major perps", "HYPE perp"],
    pnlSeries: [0, 740, 410, 1460, 2380, 1980, 3210, 4070, 4660, 5510, 6240, 7110],
    realizedPnl: 7110,
    pnlPct: 13.6,
    deployedCapital: 52300,
    dailyVolume: 468000,
    winRate: 61,
    maxDrawdown: 6.4,
    nodes: [
      { id: "liq", label: "Liquidations", x: 34, y: 78 },
      { id: "imbalance", label: "Flow Imbalance", x: 150, y: 42 },
      { id: "reversal", label: "Reversal Signal", x: 150, y: 116 },
      { id: "risk", label: "Hard Stop", x: 286, y: 78 },
    ],
    edges: [
      { from: "liq", to: "imbalance", label: "cluster" },
      { from: "liq", to: "reversal", label: "flush" },
      { from: "imbalance", to: "risk", label: "entry" },
      { from: "reversal", to: "risk", label: "exit" },
    ],
  },
  {
    id: "hl-vol-breakout",
    title: "Hyperliquid Volatility Breakout",
    creatorId: "dawnlabs",
    primarySector: "Volatility",
    sectors: ["Volatility", "Momentum"],
    productType: "Quant",
    disclosure: "PerformanceOnly",
    venues: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    markets: ["Hyperliquid Perp DEX"],
    assetClasses: ["BTC", "ETH", "SOL perps"],
    pnlSeries: [0, -220, 460, 1120, 830, 1920, 2760, 3180, 2840, 4220, 4930, 5860],
    realizedPnl: 5860,
    pnlPct: 9.8,
    deployedCapital: 59800,
    dailyVolume: 356000,
    winRate: 58,
    maxDrawdown: 7.2,
    nodes: [
      { id: "vol", label: "Vol Regime", x: 34, y: 78 },
      { id: "breakout", label: "Breakout", x: 150, y: 42 },
      { id: "trail", label: "Trail Stop", x: 150, y: 116 },
      { id: "position", label: "Position", x: 286, y: 78 },
    ],
    edges: [
      { from: "vol", to: "breakout", label: "range" },
      { from: "vol", to: "trail", label: "ATR" },
      { from: "breakout", to: "position", label: "enter" },
      { from: "trail", to: "position", label: "reduce" },
    ],
  },
  {
    id: "hl-orderflow-scalp",
    title: "Hyperliquid Orderflow Scalper",
    creatorId: "chainpilot",
    primarySector: "Liquidity",
    sectors: ["Liquidity", "Market Neutral"],
    productType: "Quant",
    disclosure: "PerformanceOnly",
    venues: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    markets: ["Hyperliquid Perp DEX"],
    assetClasses: ["HYPE", "SOL", "BTC perps"],
    pnlSeries: [0, 210, 470, 620, 920, 1180, 1570, 2030, 2440, 3010, 3480, 4020],
    realizedPnl: 4020,
    pnlPct: 7.6,
    deployedCapital: 52900,
    dailyVolume: 612000,
    winRate: 67,
    maxDrawdown: 4.8,
    nodes: [
      { id: "book", label: "Order Book", x: 34, y: 78 },
      { id: "flow", label: "Flow Score", x: 150, y: 42 },
      { id: "spread", label: "Spread Gate", x: 150, y: 116 },
      { id: "scalp", label: "Scalp", x: 286, y: 78 },
    ],
    edges: [
      { from: "book", to: "flow", label: "depth" },
      { from: "book", to: "spread", label: "bps" },
      { from: "flow", to: "scalp", label: "bias" },
      { from: "spread", to: "scalp", label: "fill" },
    ],
  },
  {
    id: "hl-margin-risk-hedge",
    title: "Hyperliquid Cross-Margin Hedge",
    creatorId: "yuna.delta",
    primarySector: "Risk Hedge",
    sectors: ["Risk Hedge", "Market Neutral"],
    productType: "Quant",
    disclosure: "PerformanceOnly",
    venues: ["Hyperliquid"],
    chains: ["Hyperliquid"],
    markets: ["Hyperliquid Perp DEX"],
    assetClasses: ["USDC collateral", "BTC / ETH / HYPE perps"],
    pnlSeries: [0, 180, 260, 510, 730, 960, 1150, 1430, 1710, 2180, 2570, 3090],
    realizedPnl: 3090,
    pnlPct: 5.0,
    deployedCapital: 61800,
    dailyVolume: 188000,
    winRate: 82,
    maxDrawdown: 2.1,
    nodes: [
      { id: "account", label: "Margin State", x: 34, y: 78 },
      { id: "exposure", label: "Net Exposure", x: 150, y: 42 },
      { id: "collateral", label: "USDC Buffer", x: 150, y: 116 },
      { id: "hedge", label: "Hedge Order", x: 286, y: 78 },
    ],
    edges: [
      { from: "account", to: "exposure", label: "risk" },
      { from: "account", to: "collateral", label: "margin" },
      { from: "exposure", to: "hedge", label: "neutral" },
      { from: "collateral", to: "hedge", label: "cap" },
    ],
  },
];
