import type {
  ChatMessage,
  GeneratedPlan,
  StrategyRun,
  TokenAsset,
  TokenTracker,
  WalletSession,
  WalletTransaction,
  WalletWorkspaceSnapshot,
} from "@/features/ai-wallet/types/walletTypes";

export const MOCK_SESSION: WalletSession = {
  id: "session-commerce-001",
  label: "Weekend plans",
  apiKeyAlias: "payment-ready",
  eoaAddress: "primary-payment-method",
  scwAddress: "session-budget-001",
  network: "Thirdeye Commerce",
  status: "ready",
  createdAt: "2026-07-09T10:24:00+09:00",
  fundingAsset: "USD",
  fundingAmount: 1200,
  gasBudgetUsd: 0,
};

export const MOCK_ASSETS: TokenAsset[] = [
  {
    id: "asset-travel",
    symbol: "Trip",
    name: "Yangpyeong camping session",
    summary: "AI summary: stay, groceries, and missing camping gear for a weekend trip.",
    firstPrompt: "나 캠핑가고 싶은데, 양평에 숙소 하나만 예약해줘.",
    contractAddress: "internal-budget:travel",
    balance: 500,
    lockedBalance: 238.7,
    fiatPrice: 1,
    change24h: -0.6,
    color: "#2563eb",
    decimals: 2,
    isMajor: true,
  },
  {
    id: "asset-shopping",
    symbol: "Shop",
    name: "Amazon purchase session",
    summary: "AI summary: approved item list, Amazon comparison, and capped checkout.",
    firstPrompt: "나 여기에 적힌 물건들 10만원 한도 내에서 아마존에서 사줘.",
    contractAddress: "internal-budget:shopping",
    balance: 100,
    lockedBalance: 96.4,
    fiatPrice: 1,
    change24h: 0.2,
    color: "#111111",
    decimals: 2,
    isMajor: true,
  },
  {
    id: "asset-food",
    symbol: "Food",
    name: "Groceries delivery session",
    summary: "AI summary: meal essentials and delivery timing for the current plan.",
    firstPrompt: "이번 주말에 필요한 장보기랑 준비물까지 한 번에 계획해줘.",
    contractAddress: "internal-budget:food",
    balance: 250,
    lockedBalance: 54.3,
    fiatPrice: 1,
    change24h: 0,
    color: "#16a34a",
    decimals: 2,
    isMajor: true,
  },
  {
    id: "asset-cash",
    symbol: "Cash",
    name: "Unassigned session balance",
    summary: "Funds not assigned to a plan yet. New chat sessions can draw from here.",
    contractAddress: "internal-budget:cash",
    balance: 4651,
    lockedBalance: 0,
    fiatPrice: 1,
    change24h: 0,
    color: "#f97316",
    decimals: 2,
    isMajor: true,
  },
];

export const MOCK_TRACKERS: TokenTracker[] = [
  {
    id: "tracker-travel",
    symbol: "Travel",
    contractAddress: "internal-budget:travel",
    enabled: true,
    source: "default",
  },
  {
    id: "tracker-shopping",
    symbol: "Shopping",
    contractAddress: "internal-budget:shopping",
    enabled: true,
    source: "default",
  },
  {
    id: "tracker-food",
    symbol: "Food",
    contractAddress: "internal-budget:food",
    enabled: true,
    source: "default",
  },
];

export const MOCK_TRANSACTIONS: WalletTransaction[] = [
  {
    id: "order-001",
    title: "Trip budget added",
    summary: "Budget for this session was prepared from your primary payment method.",
    hash: "receipt:budget-001",
    kind: "deposit",
    status: "confirmed",
    timestamp: "2026-07-09T10:24:42+09:00",
    amountLabel: "+$1,200",
  },
  {
    id: "order-002",
    title: "Yangpyeong stay reserved",
    summary: "One suitable stay was selected and reserved for the weekend.",
    hash: "receipt:stay-5842",
    kind: "execute",
    status: "confirmed",
    timestamp: "2026-07-09T10:31:08+09:00",
    amountLabel: "-₩88,000",
  },
  {
    id: "order-003",
    title: "Amazon essentials queued",
    summary: "Approved camping items were grouped under the ₩100,000 limit.",
    hash: "receipt:amazon-219",
    kind: "execute",
    status: "pending",
    timestamp: "2026-07-09T10:32:16+09:00",
    amountLabel: "₩96,400 reserved",
  },
];

export const MOCK_RUNS: StrategyRun[] = [
  {
    id: "run-824",
    title: "Yangpyeong weekend plan",
    status: "complete",
    mode: "one-shot",
    progress: 100,
    nextStep: "Reservation and shopping summary saved",
    startedAt: "2026-07-09T10:32:12+09:00",
    planId: "plan-camping-yangpyeong",
    budgetCategoryId: "asset-travel",
    budgetCategoryName: "Yangpyeong camping session",
    lockedAssets: [
      {
        symbol: "Trip",
        amount: 238.7,
        usdValue: 238.7,
      },
    ],
  },
  {
    id: "run-219",
    title: "Amazon item list",
    status: "running",
    mode: "one-shot",
    progress: 78,
    nextStep: "Waiting for purchase confirmation",
    startedAt: "2026-07-09T10:24:07+09:00",
    planId: "plan-amazon-shopping",
    budgetCategoryId: "asset-shopping",
    budgetCategoryName: "Amazon purchase session",
    lockedAssets: [
      {
        symbol: "Shop",
        amount: 96.4,
        usdValue: 96.4,
      },
    ],
  },
];

export const MOCK_PLAN: GeneratedPlan = {
  id: "plan-camping-yangpyeong",
  title: "Yangpyeong camping weekend",
  userPrompt: "나 캠핑가고 싶은데, 양평에 숙소 하나만 예약해줘.",
  summary: "숙소 예약을 먼저 고정하고, 필요한 장보기와 캠핑 준비물을 한 번에 처리할 수 있게 실행 항목을 나눴습니다.",
  explanation:
    "Thirdeye는 먼저 날짜와 목적지를 확정한 뒤 예약 가능성이 높은 숙소를 고르고, 같은 일정에 필요한 식료품과 장비를 따로 묶어 예산 안에서 처리합니다.",
  analysisSignals: ["Two-night trip", "This weekend", "Yangpyeong area", "Stay required", "Gear and groceries", "Options assembled"],
  workflowActions: [
    {
      id: "reserve-stay",
      title: "Reserve a suitable stay",
      detail: "Availability and location checked",
      status: "Reserved",
      source: "Naver Travel",
      sourceUrl:
        "https://search.naver.com/search.naver?query=%EC%96%91%ED%8F%89%20%EC%BA%A0%ED%95%91%EC%9E%A5%20%EC%98%88%EC%95%BD",
      imageAlt: "Yangpyeong campsite preview",
      placeName: "Yangpyeong riverside campsite",
      placeAddress: "Yangpyeong-gun, Gyeonggi-do",
      mapUrl:
        "https://map.naver.com/p/search/%EC%96%91%ED%8F%89%20%EA%B0%95%EB%B3%80%20%EC%BA%A0%ED%95%91%EC%9E%A5",
      timing: "Friday-Sunday",
      selected: "Riverside campsite stay • 2 nights",
      final: "₩88,000",
    },
    {
      id: "order-groceries",
      title: "Order groceries for two nights",
      detail: "Meal essentials grouped into one order",
      status: "Purchased",
      source: "Market Kurly",
      sourceUrl: "https://www.kurly.com/goods/1001635039",
      imageAlt: "Groceries selected for two nights",
      timing: "Friday • 3-5 PM",
      selected: "Breakfasts, trail lunches, dinner, snacks • 18 items",
      final: "₩54,300",
    },
    {
      id: "buy-gear",
      title: "Buy missing camping essentials",
      detail: "Gear selected from the approved list",
      status: "Purchased",
      source: "Amazon",
      sourceUrl: "https://www.amazon.com/Amazon-Basics-Outdoor-Essentials-headlamps/dp/B0DYSWT59X",
      imageAlt: "Camping essentials preview",
      timing: "Arrives before Friday",
      selected: "Rain cover, headlamp batteries, fuel canister • 3 items",
      final: "₩96,400",
    },
  ],
  timeline: [
    {
      id: "timeline-1",
      time: "Today",
      title: "Confirm trip scope",
      detail: "Destination, dates, budget ceiling, and must-have conditions are fixed.",
    },
    {
      id: "timeline-2",
      time: "Friday 3-5 PM",
      title: "Receive groceries",
      detail: "Food order arrives before departure so nothing needs to be bought on the road.",
    },
    {
      id: "timeline-3",
      time: "Friday evening",
      title: "Check in",
      detail: "Stay is reserved under the selected option and the route is ready.",
    },
    {
      id: "timeline-4",
      time: "Sunday morning",
      title: "Checkout and wrap up",
      detail: "Receipts and unused budget are returned to the session balance.",
    },
  ],
  totalLabel: "₩238,700",
  totalDetail: "Three completed actions",
  budgetCategoryId: "asset-travel",
  budgetCategoryName: "Yangpyeong camping session",
  budgetAllocatedUsd: 500,
  budgetReservedUsd: 238.7,
  generatedAt: "2026-07-09T10:31:36+09:00",
  approvalStatus: "executed",
  riskLevel: "low",
  estimatedGasUsd: 0,
  codeFingerprint: "plan_7d23e91",
  allowedAction: {
    protocol: "Thirdeye Commerce",
    contractAddress: "commerce-action",
    functionName: "reserveAndPurchase",
    parameters: [
      {
        name: "destination",
        value: "Yangpyeong",
      },
      {
        name: "dates",
        value: "Friday-Sunday",
      },
      {
        name: "budget",
        value: "Session budget",
      },
      {
        name: "vendors",
        value: "Naver Travel, Market Kurly, Amazon",
      },
    ],
  },
  lockedAssets: [
    {
      symbol: "Travel",
      amount: 307.29,
      usdValue: 307.29,
    },
  ],
  graph: {
    nodes: [
      {
        id: "intent",
        label: "Intent",
        kind: "input",
        description: "User asks Thirdeye to plan and buy",
        status: "complete",
        x: 0,
        y: 80,
      },
      {
        id: "plan",
        label: "Plan",
        kind: "plan",
        description: "Break intent into reservation and purchase actions",
        status: "complete",
        x: 240,
        y: 80,
      },
      {
        id: "guard",
        label: "Budget guard",
        kind: "guard",
        description: "Check spend limit and user confirmation",
        status: "complete",
        x: 520,
        y: 80,
      },
      {
        id: "execute",
        label: "Purchase",
        kind: "execute",
        description: "Complete only approved actions",
        status: "complete",
        x: 800,
        y: 80,
      },
    ],
    edges: [
      {
        id: "edge-intent-plan",
        from: "intent",
        to: "plan",
        label: "plan",
      },
      {
        id: "edge-plan-guard",
        from: "plan",
        to: "guard",
        label: "check",
      },
      {
        id: "edge-guard-execute",
        from: "guard",
        to: "execute",
        label: "confirm",
      },
    ],
  },
};

export const MOCK_MESSAGES: ChatMessage[] = [
  {
    id: "msg-user-001",
    role: "user",
    content: MOCK_PLAN.userPrompt,
    timestamp: "2026-07-09T10:31:12+09:00",
  },
  {
    id: "msg-assistant-001",
    role: "assistant",
    content: "플랜을 만들었어요. 아래에서 일정과 실행 항목을 확인해 주세요.",
    timestamp: "2026-07-09T10:31:36+09:00",
    planId: MOCK_PLAN.id,
  },
];

export const SUGGESTED_PROMPTS = [
  "나 캠핑가고 싶은데, 양평에 숙소 하나만 예약해줘.",
  "나 여기에 적힌 물건들 10만원 한도 내에서 아마존에서 사줘.",
  "이번 주말에 필요한 장보기랑 준비물까지 한 번에 계획해줘.",
];

export const MOCK_WORKSPACE: WalletWorkspaceSnapshot = {
  session: MOCK_SESSION,
  assets: MOCK_ASSETS,
  trackers: MOCK_TRACKERS,
  transactions: MOCK_TRANSACTIONS,
  runs: MOCK_RUNS,
  messages: MOCK_MESSAGES,
  activePlan: MOCK_PLAN,
};
