import { Node, Edge } from "@xyflow/react";
import type {
  TimeTriggerData,
  CEXActionData,
  DEXActionData,
  FunctionNodeData,
  StreamingNodeData,
} from "../components/node-editor/types";
import {
  createBinanceFuturesFundingStreamData,
  createBinanceFuturesUserDataStreamData,
  createBinanceSpotBalanceStreamData,
  createBinanceSpotPriceStreamData,
} from "./binance-demo-api";

export const getEtfDcaStrategyNodes = (): { nodes: Node[], edges: Edge[] } => {
  const nodes: Node[] = [
    {
      id: "demo-etf-group",
      type: "groupNode",
      position: { x: 50, y: 50 },
      style: { width: 780, height: 690 },
      data: {
        label: "Core ETF DCA Strategy",
        styleType: "solid"
      }
    },
    {
      id: "demo-etf-trigger",
      type: "timeTrigger",
      parentId: "demo-etf-group",
      extent: "parent",
      position: { x: 240, y: 40 },
      data: {
        label: "매달 1회 실행",
        interval: 2592000, // 30 days in seconds
        isActive: true,
      } as TimeTriggerData
    },
    {
      id: "demo-etf-balance-stream",
      type: "streamingNode",
      parentId: "demo-etf-group",
      extent: "parent",
      position: { x: 30, y: 150 },
      data: createBinanceSpotBalanceStreamData({
        label: "Binance 현물 잔고 스트림",
        outputBlocks: [
          { id: "spot-usdt-free", name: "spotUsdtFree", type: "output" },
          { id: "spot-btc-free", name: "spotBtcFree", type: "output" },
          { id: "spot-eth-free", name: "spotEthFree", type: "output" },
        ],
      }) as StreamingNodeData,
    },
    {
      id: "demo-etf-func",
      type: "functionNode",
      parentId: "demo-etf-group",
      extent: "parent",
      position: { x: 350, y: 160 },
      data: {
        label: "DCA 비율 분배기\n(가용 USDT 기준 할당)",
        functionName: "allocateDCA()",
        code: "function allocateDCA(amount) {\n  const rules = [\n    { asset: 'BTC',  weight: 55, executable: true },\n    { asset: 'ETH',  weight: 25, executable: true },\n    { asset: 'SOL',  weight: 10, executable: true },\n    { asset: 'LINK', weight: 3,  executable: false },\n    { asset: 'AAVE', weight: 2,  executable: false },\n    { asset: 'Cash', weight: 5,  executable: false }\n  ];\n\n  let btcAmount = 0, ethAmount = 0, solAmount = 0;\n  let reserveBudget = 0;\n\n  for (const rule of rules) {\n    const notional = amount * (rule.weight / 100);\n    if (rule.executable) {\n      if (rule.asset === 'BTC') btcAmount = notional;\n      if (rule.asset === 'ETH') ethAmount = notional;\n      if (rule.asset === 'SOL') solAmount = notional;\n    } else {\n      reserveBudget += notional;\n    }\n  }\n\n  return {\n    btcAmount,\n    ethAmount,\n    solAmount,\n    reserveBudget\n  };\n}",
        inputBlocks: [{ id: "ib1", name: "spotUsdtFree", type: "input" }],
        outputBlocks: [
          { id: "ob-btc", name: "btcAmount", type: "output" },
          { id: "ob-eth", name: "ethAmount", type: "output" },
          { id: "ob-sol", name: "solAmount", type: "output" }
        ],
        viewMode: "node"
      } as FunctionNodeData
    },
    {
      id: "demo-etf-act-btc",
      type: "actionNode",
      parentId: "demo-etf-group",
      extent: "parent",
      position: { x: 30, y: 390 },
      data: {
        label: "Buy BTC (55%)",
        actionType: "CEX",
        exchange: "Binance",
        symbol: "BTC/USDT",
        side: "BUY",
        orderType: "MARKET",
        amount: "{{DCA 비율 분배기.btcAmount}}",
        amountType: "FIXED",
        inputBlocks: [{ id: "ib-btc", name: "btcAmount", type: "input"}],
        outputBlocks: [],
        isExpanded: false,
      } as CEXActionData
    },
    {
      id: "demo-etf-act-eth",
      type: "actionNode",
      parentId: "demo-etf-group",
      extent: "parent",
      position: { x: 470, y: 390 },
      data: {
        label: "Buy ETH (25%)",
        actionType: "CEX",
        exchange: "Binance",
        symbol: "ETH/USDT",
        side: "BUY",
        orderType: "MARKET",
        amount: "{{DCA 비율 분배기.ethAmount}}",
        amountType: "FIXED",
        inputBlocks: [{ id: "ib-eth", name: "ethAmount", type: "input"}],
        outputBlocks: [],
        isExpanded: false,
      } as CEXActionData
    },
    {
      id: "demo-etf-act-sol",
      type: "actionNode",
      parentId: "demo-etf-group",
      extent: "parent",
      position: { x: 250, y: 580 },
      data: {
        label: "Buy SOL (10%)",
        actionType: "CEX",
        exchange: "Binance",
        symbol: "SOL/USDT",
        side: "BUY",
        orderType: "MARKET",
        amount: "{{DCA 비율 분배기.solAmount}}",
        amountType: "FIXED",
        inputBlocks: [{ id: "ib-sol", name: "solAmount", type: "input"}],
        outputBlocks: [],
        isExpanded: false,
      } as CEXActionData
    }
  ];

  const edges: Edge[] = [
    { id: "e-etf0", source: "demo-etf-trigger", target: "demo-etf-balance-stream", type: "fsm", sourceHandle: "demo-etf-trigger-trigger-out", targetHandle: "demo-etf-balance-stream-func-in" },
    { id: "e-etf0b", source: "demo-etf-balance-stream", target: "demo-etf-func", type: "fsm", sourceHandle: "demo-etf-balance-stream-trigger-out", targetHandle: "demo-etf-func-func-in" },
    { id: "e-etf0c", source: "demo-etf-balance-stream", target: "demo-etf-func", type: "custom", sourceHandle: "demo-etf-balance-stream-block-spot-usdt-free-out", targetHandle: "demo-etf-func-func-in" },
    { id: "e-etf2", source: "demo-etf-func", target: "demo-etf-act-btc", type: "fsm", sourceHandle: "demo-etf-func-block-ob-btc-out", targetHandle: "demo-etf-act-btc-func-in" },
    { id: "e-etf-b1", source: "demo-etf-func", target: "demo-etf-act-btc", type: "custom", sourceHandle: "demo-etf-func-block-ob-btc-out", targetHandle: "demo-etf-act-btc-input-ib-btc-in" },
    { id: "e-etf3", source: "demo-etf-func", target: "demo-etf-act-eth", type: "fsm", sourceHandle: "demo-etf-func-block-ob-eth-out", targetHandle: "demo-etf-act-eth-func-in" },
    { id: "e-etf-b2", source: "demo-etf-func", target: "demo-etf-act-eth", type: "custom", sourceHandle: "demo-etf-func-block-ob-eth-out", targetHandle: "demo-etf-act-eth-input-ib-eth-in" },
    { id: "e-etf4", source: "demo-etf-func", target: "demo-etf-act-sol", type: "fsm", sourceHandle: "demo-etf-func-block-ob-sol-out", targetHandle: "demo-etf-act-sol-func-in" },
    { id: "e-etf-b3", source: "demo-etf-func", target: "demo-etf-act-sol", type: "custom", sourceHandle: "demo-etf-func-block-ob-sol-out", targetHandle: "demo-etf-act-sol-input-ib-sol-in" }
  ];

  return { nodes, edges };
};

export const getPepeHedgeStrategyNodes = (): { nodes: Node[], edges: Edge[] } => {
  const nodes: Node[] = [
    {
      id: "g_strategy",
      type: "groupNode",
      position: { x: 50, y: 50 },
      style: { width: 1320, height: 980 },
      data: {
        label: "PEPE/WETH LP Hedge Strategy",
        styleType: "solid"
      }
    },
    {
      id: "g_init",
      type: "groupNode",
      parentId: "g_strategy",
      position: { x: 40, y: 50 },
      data: {
        label: "초기 진입 시퀸스 (Init)",
        styleType: "dashed-init",
        requiredStates: ["IDLE"],
        executingStates: ["IDLE"],
        isCollapsed: true,
        summaryWord: "진입",
        summaryEmoji: "🚀",
        summaryGlyph: "진",
        collapsedWidth: 196,
        collapsedHeight: 118,
      } as any,
      style: { width: 1100, height: 160 },
    },
    {
      id: "g_trigger1",
      type: "groupNode",
      parentId: "g_strategy",
      position: { x: 40, y: 220 },
      data: {
        label: "1시간 모니터링: 펀딩비 체크 후 유지 (Trigger)",
        styleType: "dashed-trigger",
        requiredStates: ["ACTIVE"],
        executingStates: [],
        isCollapsed: true,
        summaryWord: "유지",
        summaryEmoji: "🛡️",
        summaryGlyph: "유",
        collapsedWidth: 196,
        collapsedHeight: 118,
      } as any,
      style: { width: 1100, height: 160 },
    },
    {
      id: "g_trigger2",
      type: "groupNode",
      parentId: "g_strategy",
      position: { x: 40, y: 390 },
      data: {
        label: "상시 모니터링: PEPE 숏 재정렬 (Trigger)",
        styleType: "dashed-trigger",
        requiredStates: ["ACTIVE", "REBALANCING"],
        executingStates: ["REBALANCING"],
        isCollapsed: true,
        summaryWord: "PEPE 숏",
        summaryEmoji: "🐸",
        summaryGlyph: "P",
        collapsedWidth: 196,
        collapsedHeight: 118,
      } as any,
      style: { width: 1100, height: 160 },
    },
    {
      id: "g_trigger3",
      type: "groupNode",
      parentId: "g_strategy",
      position: { x: 40, y: 560 },
      data: {
        label: "상시 모니터링: ETH 숏 재정렬 (Trigger)",
        styleType: "dashed-trigger",
        requiredStates: ["ACTIVE", "REBALANCING"],
        executingStates: ["REBALANCING"],
        isCollapsed: true,
        summaryWord: "ETH 숏",
        summaryEmoji: "🔷",
        summaryGlyph: "E",
        collapsedWidth: 196,
        collapsedHeight: 118,
      } as any,
      style: { width: 1100, height: 160 },
    },
    {
      id: "g_emergency",
      type: "groupNode",
      parentId: "g_strategy",
      position: { x: 40, y: 730 },
      data: {
        label: "수동 긴급 종료 시퀸스 (Trigger)",
        styleType: "dashed-emergency",
        requiredStates: ["ACTIVE", "CLOSED"],
        executingStates: ["CLOSED"],
        isCollapsed: true,
        summaryWord: "정리",
        summaryEmoji: "🧯",
        summaryGlyph: "정",
        collapsedWidth: 196,
        collapsedHeight: 118,
      } as any,
      style: { width: 1100, height: 160 },
    },
    {
      id: "n_init_click",
      type: "clickTrigger",
      parentId: "g_init",
      position: { x: 20, y: 60 },
      data: { label: "PEPE/WETH 헤지 봇 시작", shortcut: null, isRecording: false } as any,
    },
    {
      id: "n_init_prepare",
      type: "functionNode",
      parentId: "g_init",
      position: { x: 300, y: 60 },
      data: {
        label: "초기 자금 분배 및 증거금 정렬",
        functionName: "preparePepeHedge()",
        code: "function preparePepeHedge(capital, currentPepePrice, currentEthPrice) {\n  const lpSeed = capital * 0.50;\n  const pepeShortMargin = capital * 0.25;\n  const ethShortMargin = capital * 0.25;\n\n  const basePepeQty = (lpSeed * 0.50) / currentPepePrice;\n  const baseEthQty = (lpSeed * 0.50) / currentEthPrice;\n\n  return {\n    hedgePlan: { lpSeed, pepeShortMargin, ethShortMargin },\n    targetOrders: {\n      dexLiquidityPepe: basePepeQty,\n      dexLiquidityEth: baseEthQty,\n      cexShortPepe: basePepeQty,\n      cexShortEth: baseEthQty\n    }\n  };\n}",
        inputBlocks: [],
        outputBlocks: [{ id: "out-1", name: "hedgePlan", type: "output" }, { id: "out-order", name: "targetOrders", type: "output" }],
        viewMode: "node",
      } as FunctionNodeData,
    },
    {
      id: "n_init_swap",
      type: "actionNode",
      parentId: "g_init",
      position: { x: 650, y: 40 },
      data: {
        label: "실행: PEPE/WETH LP 공급",
        actionType: "DEX",
        contractAddress: "0xPepeWethLpRouter",
        functionName: "addLiquidityPEPEWETH()",
        chainId: 1,
        inputBlocks: [{ id: "ib-lp", name: "targetOrders", type: "input"}],
        outputBlocks: [{ id: "out-2", name: "lpReady", type: "output" }],
        isExpanded: false,
      } as DEXActionData,
    },
    {
      id: "n_init_execute_pepe",
      type: "actionNode",
      parentId: "g_init",
      position: { x: 950, y: 40 },
      data: {
        label: "실행: PEPE 숏 진입",
        actionType: "CEX",
        exchange: "Binance",
        symbol: "PEPE/USDT",
        side: "SELL",
        orderType: "MARKET",
        amount: "{{초기 자금 분배 및 증거금 정렬.targetOrders.cexShortPepe}}",
        amountType: "FIXED",
        inputBlocks: [{ id: "ib-cex", name: "targetOrders", type: "input"}],
        outputBlocks: [{ id: "out-3", name: "success", type: "output" }],
        isExpanded: true,
      } as CEXActionData,
    },
    {
      id: "n_init_execute_eth",
      type: "actionNode",
      parentId: "g_init",
      position: { x: 1250, y: 40 },
      data: {
        label: "실행: ETH 숏 진입",
        actionType: "CEX",
        exchange: "Binance",
        symbol: "ETH/USDT",
        side: "SELL",
        orderType: "MARKET",
        amount: "{{초기 자금 분배 및 증거금 정렬.targetOrders.cexShortEth}}",
        amountType: "FIXED",
        inputBlocks: [{ id: "ib-cex-eth", name: "targetOrders", type: "input"}],
        outputBlocks: [{ id: "out-3-eth", name: "success", type: "output" }],
        isExpanded: true,
      } as CEXActionData,
    },
    {
      id: "n_t1_stream",
      type: "streamingNode",
      parentId: "g_trigger1",
      position: { x: 20, y: 60 },
      data: createBinanceFuturesFundingStreamData({
        label: "Binance 실시간 펀딩비 감지",
        outputBlocks: [
          { id: "out-funding", name: "fundingRateBps", type: "output" },
          { id: "out-slippage", name: "slippageBps", type: "output" }
        ],
        symbols: ["PEPEUSDT"],
      }) as StreamingNodeData,
    },
    {
      id: "n_t1_branch",
      type: "branchNode",
      parentId: "g_trigger1",
      position: { x: 380, y: 60 },
      data: {
        label: "조건 대기: 펀딩비 / 슬리피지 허용 시",
        branches: [{ id: "b1", name: "유지 가능", active: true, code: "// 상위 함수의 판단 결과가 '유지 가능'일 때만 통과시켜 액션 실행\nreturn result === '유지 가능';" }],
        inputBlocks: [
          { id: "ib-fund", name: "fundingRate", type: "input" },
          { id: "ib-slip", name: "slippage", type: "input" },
        ],
        functionName: "checkFundingStatus()",
        code: "function checkFundingStatus(fundingRateBps, slippageBps) {\n  // 펀딩비 8bps 이해, 슬리피지 20bps 이하일 경우 포지션 유지\n  if (fundingRateBps <= 8 && slippageBps <= 20) {\n    return '유지 가능';\n  }\n  return '보류';\n}",
        viewMode: "node",
      } as any,
    },
    {
      id: "n_t1_execute_pepe",
      type: "actionNode",
      parentId: "g_trigger1",
      position: { x: 750, y: 40 },
      data: {
        label: "실행: PEPE 숏 유지 보정",
        actionType: "CEX",
        exchange: "Binance",
        symbol: "PEPE/USDT",
        side: "SELL",
        orderType: "MARKET",
        amount: "250",
        amountType: "FIXED",
        inputBlocks: [],
        outputBlocks: [{ id: "out-t1-pepe", name: "success", type: "output" }],
        isExpanded: false,
      } as CEXActionData,
    },
    {
      id: "n_t1_execute_eth",
      type: "actionNode",
      parentId: "g_trigger1",
      position: { x: 1050, y: 40 },
      data: {
        label: "실행: ETH 숏 유지 보정",
        actionType: "CEX",
        exchange: "Binance",
        symbol: "ETH/USDT",
        side: "SELL",
        orderType: "MARKET",
        amount: "250",
        amountType: "FIXED",
        inputBlocks: [],
        outputBlocks: [{ id: "out-t1-eth", name: "success", type: "output" }],
        isExpanded: false,
      } as CEXActionData,
    },
    {
      id: "n_t2_stream",
      type: "streamingNode",
      parentId: "g_trigger2",
      position: { x: 20, y: 60 },
      data: createBinanceSpotPriceStreamData({
        label: "Binance 현물 가격 스트림",
        outputBlocks: [{ id: "out-price", name: "currentPrice", type: "output" }],
        symbols: ["PEPEUSDT", "ETHUSDT"],
      }) as StreamingNodeData,
    },
    {
      id: "n_t2_branch",
      type: "branchNode",
      parentId: "g_trigger2",
      position: { x: 380, y: 60 },
      data: {
        functionName: "checkRebalanceNeeded()",
        code: "function checkRebalanceNeeded(entry, current) {\n  const deviation = Math.abs(1 - current.pepePrice / entry.pepePrice);\n\n  if (deviation > 0.10) {\n     return '재정렬 필요';\n  }\n  return '유지';\n}",
        viewMode: "node",
        label: "위기 감지: PEPE 급등 / 담보 부족 시",
        branches: [{ id: "b1", name: "재정렬 필요", active: true, code: "return result === '재정렬 필요';" }],
        inputBlocks: [
          { id: "ib-price", name: "currentPrice", type: "input" },
        ],
      } as any,
    },
    {
      id: "n_t2_execute",
      type: "actionNode",
      parentId: "g_trigger2",
      position: { x: 750, y: 40 },
      data: {
        label: "실행: PEPE 숏 재정렬",
        actionType: "CEX",
        exchange: "Binance",
        symbol: "PEPE/USDT",
        side: "SELL",
        orderType: "MARKET",
        amount: "250",
        amountType: "FIXED",
        inputBlocks: [],
        outputBlocks: [{ id: "out-t2", name: "success", type: "output" }],
        isExpanded: false,
      } as CEXActionData,
    },
    {
      id: "n_t3_stream",
      type: "streamingNode",
      parentId: "g_trigger3",
      position: { x: 20, y: 60 },
      data: createBinanceSpotPriceStreamData({
        label: "Binance 현물 가격 스트림",
        outputBlocks: [{ id: "out-price-eth", name: "currentPrice", type: "output" }],
        symbols: ["ETHUSDT"],
      }) as StreamingNodeData,
    },
    {
      id: "n_t3_branch",
      type: "branchNode",
      parentId: "g_trigger3",
      position: { x: 380, y: 60 },
      data: {
        functionName: "checkEthRebalanceNeeded()",
        code: "function checkEthRebalanceNeeded(entry, current) {\n  const deviation = Math.abs(1 - current.ethPrice / entry.ethPrice);\n\n  if (deviation > 0.08) {\n     return '재정렬 필요';\n  }\n  return '유지';\n}",
        viewMode: "node",
        label: "위기 감지: ETH 급등 / 담보 부족 시",
        branches: [{ id: "b1", name: "재정렬 필요", active: true, code: "return result === '재정렬 필요';" }],
        inputBlocks: [
          { id: "ib-price-eth", name: "currentPrice", type: "input" },
        ],
      } as any,
    },
    {
      id: "n_t3_execute_eth",
      type: "actionNode",
      parentId: "g_trigger3",
      position: { x: 750, y: 40 },
      data: {
        label: "실행: ETH 숏 재정렬",
        actionType: "CEX",
        exchange: "Binance",
        symbol: "ETH/USDT",
        side: "SELL",
        orderType: "MARKET",
        amount: "250",
        amountType: "FIXED",
        inputBlocks: [],
        outputBlocks: [{ id: "out-t2-eth", name: "success", type: "output" }],
        isExpanded: false,
      } as CEXActionData,
    },
    {
      id: "n_em_click",
      type: "clickTrigger",
      parentId: "g_emergency",
      position: { x: 20, y: 60 },
      data: { label: "긴급: 모든 PEPE/WETH 포지션 종료", shortcut: null, isRecording: false } as any,
    },
    {
      id: "n_em_stream",
      type: "streamingNode",
      parentId: "g_emergency",
      position: { x: 240, y: 36 },
      data: createBinanceFuturesUserDataStreamData({
        label: "Binance 선물 포지션 스트림",
        outputBlocks: [
          { id: "pos-pepe", name: "pepeShortQty", type: "output" },
          { id: "pos-eth", name: "ethShortQty", type: "output" },
          { id: "wallet-usdt", name: "futuresWalletUsdt", type: "output" },
        ],
      }) as StreamingNodeData,
    },
    {
      id: "n_em_cex_pepe",
      type: "actionNode",
      parentId: "g_emergency",
      position: { x: 560, y: 40 },
      data: {
        label: "청산: Binance PEPE 숏 전량 정리",
        actionType: "CEX",
        exchange: "Binance",
        symbol: "PEPE/USDT",
        side: "BUY",
        orderType: "MARKET",
        amount: "{{Binance 선물 포지션 스트림.pepeShortQty}}",
        amountType: "FIXED",
        inputBlocks: [
          { id: "ib-pos-pepe", name: "pepeShortQty", type: "input" },
          { id: "ib-wallet-usdt", name: "futuresWalletUsdt", type: "input" },
        ],
        outputBlocks: [{ id: "out-em-cex-pepe", name: "positionsClosed", type: "output" }],
        isExpanded: false,
      } as CEXActionData,
    },
    {
      id: "n_em_cex_eth",
      type: "actionNode",
      parentId: "g_emergency",
      position: { x: 860, y: 40 },
      data: {
        label: "청산: Binance ETH 숏 전량 정리",
        actionType: "CEX",
        exchange: "Binance",
        symbol: "ETH/USDT",
        side: "BUY",
        orderType: "MARKET",
        amount: "{{Binance 선물 포지션 스트림.ethShortQty}}",
        amountType: "FIXED",
        inputBlocks: [
          { id: "ib-pos-eth", name: "ethShortQty", type: "input" },
          { id: "ib-wallet-usdt-eth", name: "futuresWalletUsdt", type: "input" },
        ],
        outputBlocks: [{ id: "out-em-cex-eth", name: "positionsClosed", type: "output" }],
        isExpanded: false,
      } as CEXActionData,
    },
    {
      id: "n_em_execute",
      type: "actionNode",
      parentId: "g_emergency",
      position: { x: 1160, y: 40 },
      data: {
        label: "청산: LP 회수 및 전체 USDT 변환",
        actionType: "DEX",
        contractAddress: "0xPepeWethExitRouter",
        functionName: "liquidatePepeHedge()",
        chainId: 1,
        inputBlocks: [],
        outputBlocks: [{ id: "out-em", name: "success", type: "output" }],
        isExpanded: false,
      } as DEXActionData,
    },
  ];

  const edges: Edge[] = [
    { id: "e_init_1", source: "n_init_click", target: "n_init_prepare", sourceHandle: "n_init_click-trigger-out", targetHandle: "n_init_prepare-func-in", type: "custom" },
    { id: "e_init_2", source: "n_init_prepare", target: "n_init_swap", sourceHandle: "n_init_prepare-block-out-1-out", targetHandle: "n_init_swap-func-in", type: "custom" },
    { id: "e_init_data1", source: "n_init_prepare", target: "n_init_swap", sourceHandle: "n_init_prepare-block-out-order-out", targetHandle: "n_init_swap-input-ib-lp-in", type: "custom" },
    { id: "e_init_3", source: "n_init_swap", target: "n_init_execute_pepe", sourceHandle: "n_init_swap-success-out", targetHandle: "n_init_execute_pepe-func-in", type: "custom" },
    { id: "e_init_data2", source: "n_init_prepare", target: "n_init_execute_pepe", sourceHandle: "n_init_prepare-block-out-order-out", targetHandle: "n_init_execute_pepe-input-ib-cex-in", type: "custom" },
    { id: "e_init_4", source: "n_init_execute_pepe", target: "n_init_execute_eth", sourceHandle: "n_init_execute_pepe-success-out", targetHandle: "n_init_execute_eth-func-in", type: "custom" },
    { id: "e_init_data3", source: "n_init_prepare", target: "n_init_execute_eth", sourceHandle: "n_init_prepare-block-out-order-out", targetHandle: "n_init_execute_eth-input-ib-cex-eth-in", type: "custom" },

    { id: "e_t1_1", source: "n_t1_stream", target: "n_t1_branch", sourceHandle: "n_t1_stream-trigger-out", targetHandle: "n_t1_branch-branch-in", type: "custom" },
    { id: "e_t1_block1", source: "n_t1_stream", target: "n_t1_branch", sourceHandle: "n_t1_stream-block-out-funding-out", targetHandle: "n_t1_branch-input-ib-fund-in", type: "custom" },
    { id: "e_t1_block2", source: "n_t1_stream", target: "n_t1_branch", sourceHandle: "n_t1_stream-block-out-slippage-out", targetHandle: "n_t1_branch-input-ib-slip-in", type: "custom" },
    { id: "e_t1_2", source: "n_t1_branch", target: "n_t1_execute_pepe", sourceHandle: "n_t1_branch-branch-b1-out", targetHandle: "n_t1_execute_pepe-func-in", type: "custom" },
    { id: "e_t1_3", source: "n_t1_execute_pepe", target: "n_t1_execute_eth", sourceHandle: "n_t1_execute_pepe-success-out", targetHandle: "n_t1_execute_eth-func-in", type: "custom" },

    { id: "e_t2_1", source: "n_t2_stream", target: "n_t2_branch", sourceHandle: "n_t2_stream-trigger-out", targetHandle: "n_t2_branch-branch-in", type: "custom" },
    { id: "e_t2_block1", source: "n_t2_stream", target: "n_t2_branch", sourceHandle: "n_t2_stream-block-out-price-out", targetHandle: "n_t2_branch-input-ib-price-in", type: "custom" },
    { id: "e_t2_2", source: "n_t2_branch", target: "n_t2_execute", sourceHandle: "n_t2_branch-branch-b1-out", targetHandle: "n_t2_execute-func-in", type: "custom" },
    { id: "e_t3_1", source: "n_t3_stream", target: "n_t3_branch", sourceHandle: "n_t3_stream-trigger-out", targetHandle: "n_t3_branch-branch-in", type: "custom" },
    { id: "e_t3_block1", source: "n_t3_stream", target: "n_t3_branch", sourceHandle: "n_t3_stream-block-out-price-eth-out", targetHandle: "n_t3_branch-input-ib-price-eth-in", type: "custom" },
    { id: "e_t3_2", source: "n_t3_branch", target: "n_t3_execute_eth", sourceHandle: "n_t3_branch-branch-b1-out", targetHandle: "n_t3_execute_eth-func-in", type: "custom" },

    { id: "e_em_1", source: "n_em_click", target: "n_em_stream", sourceHandle: "n_em_click-trigger-out", targetHandle: "n_em_stream-func-in", type: "custom" },
    { id: "e_em_2", source: "n_em_stream", target: "n_em_cex_pepe", sourceHandle: "n_em_stream-trigger-out", targetHandle: "n_em_cex_pepe-func-in", type: "custom" },
    { id: "e_em_data1", source: "n_em_stream", target: "n_em_cex_pepe", sourceHandle: "n_em_stream-block-pos-pepe-out", targetHandle: "n_em_cex_pepe-input-ib-pos-pepe-in", type: "custom" },
    { id: "e_em_data2", source: "n_em_stream", target: "n_em_cex_pepe", sourceHandle: "n_em_stream-block-wallet-usdt-out", targetHandle: "n_em_cex_pepe-input-ib-wallet-usdt-in", type: "custom" },
    { id: "e_em_3", source: "n_em_cex_pepe", target: "n_em_cex_eth", sourceHandle: "n_em_cex_pepe-success-out", targetHandle: "n_em_cex_eth-func-in", type: "custom" },
    { id: "e_em_data3", source: "n_em_stream", target: "n_em_cex_eth", sourceHandle: "n_em_stream-block-pos-eth-out", targetHandle: "n_em_cex_eth-input-ib-pos-eth-in", type: "custom" },
    { id: "e_em_data4", source: "n_em_stream", target: "n_em_cex_eth", sourceHandle: "n_em_stream-block-wallet-usdt-out", targetHandle: "n_em_cex_eth-input-ib-wallet-usdt-eth-in", type: "custom" },
    { id: "e_em_4", source: "n_em_cex_eth", target: "n_em_execute", sourceHandle: "n_em_cex_eth-success-out", targetHandle: "n_em_execute-func-in", type: "custom" },

    { id: "fsm-1", source: "g_init", target: "g_trigger1", sourceHandle: "g_init-fsm-source", targetHandle: "g_trigger1-fsm-target", type: "fsmEdge", data: { label: "완료 시 ACTIVE 진입", color: "#10b981" }, selectable: false, focusable: false, deletable: false } as any,
    { id: "fsm-2", source: "g_init", target: "g_trigger2", sourceHandle: "g_init-fsm-source", targetHandle: "g_trigger2-fsm-target", type: "fsmEdge", data: { label: "완료 시 ACTIVE 진입", color: "#10b981" }, selectable: false, focusable: false, deletable: false } as any,
    { id: "fsm-2b", source: "g_init", target: "g_trigger3", sourceHandle: "g_init-fsm-source", targetHandle: "g_trigger3-fsm-target", type: "fsmEdge", data: { label: "완료 시 ACTIVE 진입", color: "#10b981" }, selectable: false, focusable: false, deletable: false } as any,
    { id: "fsm-3", source: "g_trigger2", target: "g_trigger1", sourceHandle: "g_trigger2-fsm-source", targetHandle: "g_trigger1-fsm-target", type: "fsmEdge", data: { label: "PEPE 재정렬 완료 → ACTIVE 유지", color: "#a78bfa" }, selectable: false, focusable: false, deletable: false } as any,
    { id: "fsm-3b", source: "g_trigger3", target: "g_trigger1", sourceHandle: "g_trigger3-fsm-source", targetHandle: "g_trigger1-fsm-target", type: "fsmEdge", data: { label: "ETH 재정렬 완료 → ACTIVE 유지", color: "#60a5fa" }, selectable: false, focusable: false, deletable: false } as any,
    { id: "fsm-4", source: "g_trigger1", target: "g_emergency", sourceHandle: "g_trigger1-fsm-source", targetHandle: "g_emergency-fsm-target", type: "fsmEdge", data: { label: "ACTIVE 중 수동 종료 가능", color: "#ef4444" }, selectable: false, focusable: false, deletable: false } as any,
  ];

  return { nodes, edges };
};
